# Algoritmos y Estructuras de Datos. 

## - Clase 6 - Encapsulamiento, Módulos y Objetos -

# Funciones

## Funciones Recursivas

Python nos permite una declaración sencilla de **funciones recursivas**, solamente debemos *"llamar a la función, dentro del cuerpo de la (misma) función'*. 

Una definición correcta de una función recursiva, debera tener el cuenta lo siguiente:

- Existencia de un **caso base** o inicial de manera *especial*, es decir cuando la función retorna un valor (no hay llamada recursiva), ya que sino, la función prodria nunca terminar. 


Manejo standard del caso base: 

- Utilizando un  $\normalsize \color{green}{\textsf{ if }}$, como veremos a continuación.
- Luego podremoms: 
    - Terminar la función
    - Terminar y devolver un valor que indicará un error en la ejecución de la función 
    - Opcionalmente podemos informar del error, utilizando los errores predefinidos provistos por Python utilizando el comando $\normalsize \color{green}{\textsf{ raise }}$.  


El comando $\normalsize \color{green}{\textsf{ raise }}$ es invocado de la siguiente forma:

$\normalsize \color{green}{\textsf{ raise }}$ $\texttt{ AssertionError ( string )}$

In [ ]:
# Secuencia de Fibonacci.
# [ 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, . . . ]
def Fibo(n):

    "Definición: F(n) = F(n-1) + F(n-2), F(1) = F(0) = 1"

    if n<0:
        #raise ValueError("Fibonacci terms begin at 0") # sin este error, Fibo(-1) etrara en un ciclo eterno.
        print("error")
        return -1
    
    if n==0:
        return 1 # Primer caso base
    elif n==1:
        return 1 # Segundo caso base
    else:
        return Fibo(n-1)+Fibo(n-2) ## ESTA ES LA LLAMADA RECURSIVA

In [ ]:
print(Fibo(100))

In [ ]:
# Cálculo recursivo del factorial de un número n.
def factorial(n):
    if type(n) is not int:
        raise ValueError("N debe ser un numero entero")
    elif n <0 :
        raise ValueError("N debe ser mayor a 0")
    else:     
        if n<=1:
            return 1
        else: 
            return n * factorial(n-1)

In [ ]:
print(factorial(5))

Como para el caso de la generación de conjuntos, listas, etc. por comprención. Podemos utilizar cualquier función, incluso aquellas que definimos nosotros. 

In [ ]:
# Ejemplo lista por comprención

[Fibo(n) for n in range(0,20)] # Para n>30 la performace es muy lenta. 

El uso de funciones recursivas no debe ser abusado. Este tipo de funciones nos permite la facilidad de escritura de una función, aunque generalmente requieren el uso de mucha memoria. *(Luego veremos cómo mejorar esto)*.


In [ ]:
# Ejemplo: Fibonacci Iterativo
def Fiboiter(n):
    if n<0:
        raise ValueError("La secuencia de Fibonacci comienza en '0'") # si no comprabos que el parámetro es un 
                                                                      # nro. entero, por ejemplo, llamar a Fibo(-1) 
                                                                      # causara que la función nunca termine.
    elif n==0:
        return 1 # Primer caso base
    elif n==1:
        return 1 # Segundo caso base
    else:
        x=1 # elemento 0
        y=1 # elemento 1ro
        for i in range(1,n):
            # elemento 'x' i-1-esimo, e 'y' sera el i-esimo elemento
            x, y = y, x + y
            # elemento 'x' i-esimo, e 'y' sera el i+1-esimo elemento
        return y

In [ ]:
N=10
print(Fibo(N),"=",Fiboiter(N))

In [ ]:
print(Fiboiter(100))

In [ ]:
# Secuencia de Fibonacci contando la cantidad de llamaradas recursivas
t=0
def Fibo(n):

    """n debe ser un número entero 
    "F(n)=F(n-1)+F(n-2), F(1)=F(0)=1"""
    
    global t # la variable t será considerada como global
    t+=1     # hacemos algo con t
    if n<0:
        raise ValueError("Fibonacci terms begin at 0") 
    elif n==0:
        return 1 
    elif n==1:
        return 1 
    else:
        return Fibo(n-1)+Fibo(n-2)
# Es posible estimar la cantidad de llamadas a la función? 

In [ ]:
help(Fibo)

In [ ]:
t=0
2*Fibo(20)-1

In [ ]:
t

## Funciónes y el "alcanze" (scope) de las variables

El *alcanze* de una variable $\texttt{v}$ es el conjunto de lineas de código, en donde la variable es comprendida. Es decir, donde el nombre de variable $\texttt{v}$ esta asignado a un valor. 

A priori, es simple: 

"*si la variable* $\texttt{v}$ *esta definida en la linea* $n$ *el alcanze de la variable será cualquier linea* $m > n$ ".


Esto se complica cuando introducimos funciones, estas pueden (o no) cambiar el alcanze de una variable. Esta situación se complica aún más cuando tenemos *funciones anidadas*, es decir, funciones dentro de otras funciones. 

A continuación veremos algunos ejemplos: 


In [ ]:
# Investigar en los siguientes ejemplos: - qué será impreso por pantalla? 
#                                        - cuál es el valor de x luego de cada llamada a una función? 
#                                        - habra algún mensaje de error?

x=2

def ExVar1():
    print(x)
    
def ExVar2():
    x=5
    print(x)
    
def ExVar3():
    x=5    
    def ExVar11():
        global x
        print(x)       
    ExVar11()    
    print(x)
    
def ExVar4():
    print(x)
    print('x=1')

In [ ]:
ExVar3()

La razón principal por la cual los variables tienen un alcanze predefinido es para evitar **efectos secundarios**. Es decir, cambiar los valores de variables que pasamos por argumento y afectar el resto del código. Por ello, por defecto, el alcanze de las variables es **dentro del cuerpo de la función**. 

Notar que aquellas variables **invocadas que no están en el cuerpo de la función no existiran**.


De esta menera podemos "proteger" las variables fuera de la función.

Es posible cambiar este comportamiento. Debemos usar el comando $\normalsize \color{green}{\textsf{ global }}$ o $\normalsize \color{green}{\textsf{ nonlocal }}$. La diferencia entre ambos es sutil: 

Sea una variable $\texttt{v}$:

- Con el comando $\normalsize \color{green}{\textsf{ global }}$ $\texttt{v}$, la variable $\texttt{v}$ será usada como una variable global (externa a la función), perteneciente al código con mayor alcanze. 

- Con el comando $\normalsize \color{green}{\textsf{ nonlocal }}$ $\texttt{v}$, la variable $\texttt{v}$ será aquella cual alcanze es de **un nivel superioir**, es decir, en funciónes anidadas, aquella que tenga mayor alcanze.  


Debemos notar que al utilizar $\normalsize \color{green}{\textsf{ nonlocal }}$ en funciones recursivas, generara un error del tipo **SyntaxError**. 



## Añadir nuestra función al comando "help"

Si queremos añadir texto el cual será impreso cuando llamamos a la función $\normalsize \color{green}{\textsf{ help }}$, simplemente debemos escribir una(s) linea(s) de texto luego de la definición de nustra función.


In [ ]:
def nicelydocumented():
    "Esta función devuelve TRUE siempre."
    "Esta linea no será vista" 
    
    return True

In [ ]:
nicelydocumented()

In [ ]:
help(nicelydocumented)

Como hemos visto en las definiciones de algunas anteriores, es posible escribir más de una linea de texto, utilizando cualquier método para escribir strings largos (i.e. triple comillas o la barra al final de cada linea).  

# Módulos en Python


Para que nos siven? Nos permiten definir nuestras propias funciones, bloques de codigo, metodos, pbjetos, tipos de datos, etc. 
Cuando desarrollamos, aunque es possible hacerlo de manera individual, **requiere mucho tiempo y esfuerzo**, además de se debe considerar la (posible) **falta de eficiencia u otimización** del codigo.

El comando $\normalsize \color{green}{\textsf{import}}$ nos permite utilizar funciones y objetos definidos fuera de las funciones pre-definidas en Python.

Por qué estas funciones no estas dentro de Python? Son muchas y muy especificas a cada dominio. A raíz de esto, los siguientes problemas aparecen: 

- Uso ineficiente de memoria.
- Conflictos de nombres.


Usar $\textit{módulos}$ nos permite trabajar de forma colaborativa, en equipos. De esta manera se podrán abordar projectos de gran magnitud. 


## Cómo usar $\normalsize \color{green}{\textsf{import}}$ ?


Hay dos fromas de usar el comando $\normalsize \color{green}{\textsf{import}}$.


### Importar solo un módulo.

$\normalsize \color{green}{\textsf{ import }} \texttt{nombre\_módulo}$


Luego podremos llamar a la cualquier función $\texttt{func}$ definida dentro del módulo $\texttt{nombre\_módulo}$, de la siguiente forma: $\texttt{nombre\_módule.func}$.

In [1]:
#Ejemplo nombramiento directo
import random
random.randrange(100)

36

In [2]:
import numpy
numpy.pi  #numpy.pi es la aproximación del número pi.

dir(numpy) #dir sirve para ver toda la interfaz publica y todos los metodos que el objeto o clase soporta!

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

De forma técnica, el comando $\normalsize \color{green}{\textsf{import}}$ $\texttt{ nombre\_módulo }$ ,  genera una nueva variable $\texttt{nombre\_módulo}$ tipo $\textit{módulo}$. Luego, las funciones y/o métodos definidas en el módulo pueden ser llamados o invocados desde nuestro codigo. 


In [3]:
print(type(random)) # Tipo : module (módulo)
print(type(random.randrange)) # Tipo : method (método)
print(type(numpy.pi))

<class 'module'>
<class 'method'>
<class 'float'>


In [4]:
randrange(100) # Esto genera un error del tipo "NameError" porque la función randrange no esta definida. 

NameError: name 'randrange' is not defined

También es posible cambiar el nombre de los módulos, por otro, generalmente más corto.

$\normalsize \color{green}{\textsf{import}}$ $\texttt{ nombre\_módulo}$ $\normalsize \color{green}{\textsf{as}}$ $\texttt{nuevo\_nombre}$

In [7]:
import math as m # el nommbre 'math' no es asociado al modulo (el nombre de variable esta "libre") 
                 # m es el objeto que contiene las funciones del módulo math. 
print(m.pi) # funciona...
math.pi # NameError

3.141592653589793


NameError: name 'math' is not defined

### Importar objectos desde un módulo

La otra manera de importar funciones (objetos, métodos, etc.) definidas en un módulo es asignando un nuevo monbre para ellas:

$\normalsize \color{green}{\textsf{ from }}$ $\texttt{ nombre\_módulo}$ $\normalsize \color{green}{\textsf{ import }}$ $\texttt{algo\_1, algo\_2, ...}$ $\normalsize \color{green}{\textsf{ as }}$ $\texttt{nuevo\_mombre\_1, nuevo\_nombre\_2, ...}$


In [8]:
from math import pi as sliceofpie # sliceofpie es un número con el valor de math.pi
from math import pi # el comando "as" es opcional
pi == sliceofpie # Son Iguales

True

Si queremos importar un módulo de manera **"completa"**, es decir, todas las funciones, objetos, etc, invocamos el siguiente comando:


$\normalsize \color{green}{\textsf{ from }}$ $\texttt{nombre\_módulo}$ $\normalsize \color{green}{\textsf{import}}$ $\texttt{ * }$


In [10]:
#import math 
#math.pi 

from random import *
randrange(100)

from math import *
pi

NameError: name 'math' is not defined

In [11]:
import random
for x in  dir(random): #Funciones provistas por Python (built-in functions).  
    print (x, end= " - ")
    
help(random)

BPF - LOG4 - NV_MAGICCONST - RECIP_BPF - Random - SG_MAGICCONST - SystemRandom - TWOPI - _ONE - _Sequence - _Set - __all__ - __builtins__ - __cached__ - __doc__ - __file__ - __loader__ - __name__ - __package__ - __spec__ - _accumulate - _acos - _bisect - _ceil - _cos - _e - _exp - _floor - _index - _inst - _isfinite - _log - _os - _pi - _random - _repeat - _sha512 - _sin - _sqrt - _test - _test_generator - _urandom - _warn - betavariate - choice - choices - expovariate - gammavariate - gauss - getrandbits - getstate - lognormvariate - normalvariate - paretovariate - randbytes - randint - random - randrange - sample - seed - setstate - shuffle - triangular - uniform - vonmisesvariate - weibullvariate - Help on module random:

NAME
    random - Random variable generators.

MODULE REFERENCE
    https://docs.python.org/3.11/library/random.html
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include featur

Aunque los módulos mas usados, toman en cuenta la definición de nombres de manera cuidadosa para no generar conflictos. Es una buena practica evitar importar "todo" (utilizando asterisco) si importaremos mas de un módulo. 


## Algunos de los módulos mas utilizados

Nota: algunos de estos módulos vienen provistos dependiendo de que versión y via que método instalamos Python. Los módulos qué no esten presentes, deben ser instalados manualmente o mediante la herramienta **"pip"**.  Tambien se puede instalar py -m pip install [NOMBREDELMODULO]


### Módulo math

Para la mayoría de los módulos "comunes" de Python, la documentación es extensiva y clara. Ver Documentación del módulo $\texttt{math}$: https://docs.python.org/es/3.6/library/math.html

La libreria $\texttt{math}$ contiene funciones comunes (logaritmoms, exponenciales, trigonometricas, ...) y algunas constantes ($\pi$, $e$, ...), además de algunos otras definiciones, por ejemplo $\texttt{inf}$ ($+\infty$) y $\texttt{nan}$ que "No Representa a un Número" (Not A Number) y es del tipo número de punto flotante". 


In [12]:
from math import inf,nan

print(inf+inf)
print(1/inf) 
print(inf-inf)# "Indeterminado" aunque no genera error  
print()
print(nan)

inf
0.0
nan

nan


In [13]:
1.0/0.0 # Infinito no es un resultado valido. 

ZeroDivisionError: float division by zero

In [14]:
from math import log
log(0) #no -inf definido (solo +inf)

ValueError: math domain error

### Módulo numpy

Su Documentación completa está disponible aqui: http://www.numpy.org. Particularmente interesante para problemas mathematicos. 
Nos ofrece un nuevo tipo de dato "arreglo" (array), tambien llamados "vectores", cuando todos los elementos son del mismo tipo.  


In [15]:
import numpy as np

In [16]:
v=np.array([[1,1],[1,1]])# Crea un arreglo de 2 x 2 (es decir, una matríz).  
                         # v= [ 1 | 1
                         #      1 | 1 ]
print(v)

print([[1,1],[1,1]])

type(v)

[[1 1]
 [1 1]]
[[1, 1], [1, 1]]


numpy.ndarray

In [17]:
v+=v
print(v)

[[2 2]
 [2 2]]


In [18]:
v=np.array([[1,2],[3,4]])
print(v)
print(v[0][1]) # Podemos indexar los elementos de un array
v[0][1]=5 
print(v)
w=v     # Los arrays son objetos "mutables".
w[0][1]=3
print(w,'\n',v)

[[1 2]
 [3 4]]
2
[[1 5]
 [3 4]]
[[1 3]
 [3 4]] 
 [[1 3]
 [3 4]]


In [19]:
np.array([[True,2.0],[0+1j,0.1],(3+7*1j,-np.pi)]) # La *función* array normalizara los datos 
                                                  # que ingresamos por parametros. 

array([[ 1.        +0.j,  2.        +0.j],
       [ 0.        +1.j,  0.1       +0.j],
       [ 3.        +7.j, -3.14159265+0.j]])

In [20]:
np.zeros([2,3,4,3]) # podemos crear arreglos multi-dimensionales

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

Además tenemos provisto el tipo $\textit{Matríz}$. 

In [21]:
M=np.matrix([[0,1j],[1j,0]]) # Tipo : matrix
print(M.conjugate()) # Retorna wl conjugado de la matríz.
print(M*M)

[[0.-0.j 0.-1.j]
 [0.-1.j 0.-0.j]]
[[-1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]


In [22]:
N=M     # Las matrices son elementos mutables.
N[0,1]=2713
print(M)

[[   0.+0.j 2713.+0.j]
 [   0.+1.j    0.+0.j]]


Existen muchos más métodos relacionados al manejo de matrices y algebras, contenidos en el $\textit{sub-módulo}$ $\texttt{linalg}$. 



In [23]:
from numpy import linalg as LA
eigvalues,eigvectors=LA.eigh(np.matrix([[10,1],[1,2]])) #eigh calcula los eigenvalues de matrices simetricas-hemitaneas
print(eigvalues)

[ 1.87689437 10.12310563]


También podemos generar estructuras de mayor deminesión, i.e. Tensores. 

### Módulo scipy

Su Documentación completa está disponible aqui: https://www.scipy.org. Contiene a los módulos $\texttt{numpy}$ (analisis numerico), $\texttt{sympy}$ (computación simbolica), y otras heramientas útiles que veremos luego.


### Módulo random

Como lo indica su nombre, se utiliza para generar valores (u objetos) aleatorios. 


In [24]:
import random

In [25]:
random.random() # Retorna un número de punto flotante aleatorio entre 0 y 1 (igual que la calculadora)

0.5787599478365688

In [26]:
random.randrange(0,4) # Retorna un entero aleatorio entre 0 y 3 (incluido)

2

In [27]:
Meses=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
random.shuffle(Meses) #Mezcla los meses (la lista Meses ha sido cambiada)
Meses

['Apr',
 'Feb',
 'Jun',
 'May',
 'Jul',
 'Oct',
 'Sep',
 'Jan',
 'Aug',
 'Mar',
 'Nov',
 'Dec']

In [28]:
random.sample(Meses,k=12) # Retorna una muestra de 5 elementos de la población Meses
#Comparar con las opciones: random.shuffle(L) and random.sample(L,len(L))

['Nov',
 'Dec',
 'Aug',
 'Feb',
 'Mar',
 'Jun',
 'Sep',
 'Apr',
 'May',
 'Jan',
 'Jul',
 'Oct']

In [29]:
#Ejercicio : Crear una matríz simetrica de tamaño 100 y calcular sus eigenvalues
from numpy import matrix
import random
ListtoMatrix=[]
for x in range(0,100):
    Ligne=[]
    for y in range(0,x):
        Ligne.append(ListtoMatrix[y][x])
    for y in range(x,100):
        Ligne.append(random.randrange(-10,10))
    ListtoMatrix.append(Ligne)
eigval,eigvect=LA.eigh(matrix(ListtoMatrix))
len(eigval)
eigval


array([-114.14017769, -106.76011893, -102.70884168,  -99.52519307,
        -94.50697486,  -88.61353161,  -85.1498409 ,  -80.9558835 ,
        -78.99893768,  -77.28781545,  -76.21739958,  -72.21847286,
        -69.17898012,  -68.57868272,  -67.69146956,  -64.12700179,
        -62.72114073,  -60.63320422,  -60.26236424,  -57.74134   ,
        -54.88281737,  -54.50569325,  -52.96608028,  -50.04413193,
        -49.37101325,  -45.39471837,  -43.46889745,  -41.94744819,
        -36.46279509,  -36.08416506,  -35.7807983 ,  -33.81396066,
        -30.79402708,  -29.3075421 ,  -27.80590881,  -26.32874114,
        -25.89627726,  -22.42201033,  -21.70793221,  -20.56883103,
        -19.19130748,  -17.44544239,  -14.66437558,  -13.62209775,
        -11.16691663,   -9.51216847,   -8.58739377,   -7.4806063 ,
         -4.19302054,   -3.00453991,   -2.11763369,    2.04098709,
          3.5646682 ,    6.13047158,    8.76234098,    9.23679338,
         10.65318493,   11.93751564,   14.02029336,   15.72363

In [30]:
#Ejercicio: Paradoja del Cumpleaños. Dentro de un grupo de 10 personas, asumiendo que 
#sus cumpleños siguen una distribución normal sobre los 365 dias de año. Calcular una aproximación
#de la probabilidad que dos personas cumplan años el mismo día.
#Mismo ejercicio, pero para 30 personas.

N=10000 #Numero de iteraciones (tests)
Npeople=10 #Número de personas. 
S=0     #+1 si no hay cumpleños que iguales, 0 en otro caso.
for ntest in range(0,N):
    Lbirthday=[]
    for x in range(0,Npeople):
        birthday=random.randrange(0,366)
        if birthday in Lbirthday:     # Verificar si dos personas tienen el mismo cumpleaños
            test=0             # Mantendremos S = 0. 
            break              # Salimos del ciclo.
        else:
            Lbirthday.append(birthday) #Añadir el cumpleaños a la lista de cumpleaños para ese día.
    
    if len(Lbirthday)==Npeople:   # Si la lista de cumpleños Lbirthday es igual a Npeople, entonces todas
                                  # las personas tienen diferentes cumpleaños. 
        test=1
        
    S+=test                   # Añadimos los resultados del test a la variable S

print(S/N) # Mostrar porcentaje.  




0.8891


In [31]:
# Ejercicio : Supongamos que hacemos una "tirada" de  10 dados. 
    # Ganaremos $200 si la suma de los valores esta entre los 10 y 23. 
    # Perderemos $1600 si la suma de los valores es 24 o 48.
    # Ganaremos $2500 si la suma de los valores es 42.
    # Perderemos $500 en cualquier otro caso.
  # Deberiamos jugar a este juego?


N=10000 #Número de iteraciones o "tests"
S=0     #Suma total del dinero ganado/perdido 

for ntest in range(0,N):
    
    dicesvalue=0           #Inicialización
    
    for ndice in range(0,10):      #" tiramos los dados 10 veces" 
        dicesvalue+=random.randrange(1,7)  # "tirada" de **un** dado 
    
    if dicesvalue<= 23:   # Aplicamos las reglas del juego
        S+=200
    elif dicesvalue==10 or dicesvalue==23:
        S-=1600
    elif dicesvalue==42:
        S+=2500
    else:
        dicesvalue-=500
        
print(S/N)  # El promedio S/N es una buen estimador de la "espranza" de las ganancias. 



84.96


## Importar módulos escritos por el usuario

Podemos importar nuestras propios módulos, para ello, veremos como método de encapsilación: **Clases**. 


## Preliminares : Functiones vs. Métodos

Python nos provee de dos formas de ejecutar instrucciones y retornar valoes, dados una serie de parametros. Podemos llamar a una **función** o a un **método**. 

Ya hemos visto algunos ejemplos de funciones como $\normalsize \color{green}{\textsf{print}}$, $\normalsize \color{green}{\textsf{len}}$,$\dots$. 

Un método es tipo específico de "función" y es llamdo (o invocado) de la siguiente forma: 


Si $\texttt{obj}$ es un objeto del tipo **type** y **method** es un método asociado al tipo **type**, entonces llamaremos (o invocaremos) al método utilizando $\texttt{obj.method}(\cdot)$ en donde, $\cdot$ puede contener parametros o no. 

In [32]:
c='ertl'
print(len(c)) # Función
c.index('e')  # Método

4


0

De manera practica no existen muchas diferencias entre métodos y funciones. Las funciones serán definidas como objetos inependientes, mientras que los métodos están definidas dentro de un tipo de objeto y no "existiran" fuera de este.


In [ ]:
#len=2
#len(c) # No tendra ningun sentido

Funciones y métodos pueden retornar un valor (como en el caso de **len**) o sólamente realizar una acción (como en el caso de **print**). También pueden modificar otros objetos. 

In [33]:
type(print(c)) # print (ejecutado) no tiene valor o tipo.

ertl


NoneType

# Clases en Python

En Python, una $\textit{Clase}$ nos permite definir nuestros propies tipos de objetos. Debemos pensar en una Clase, cómo un "template" de nuestros objetos, donde definiremos sus **atributos** (variables internas) y/o **métodos** ("comportamientos", o funciones internas). 

Ambas pueden ser invoacadas regularmente de la siguiente forma: $\texttt{obj.name}$. 


## Definición

In [34]:
class MyfirstClass(): pass   # pass Es para no escribir nada y no salga error
    # Atributos 
    # Métodos
    
x=MyfirstClass() # Define un objecto del Tipo 'MyfirstClass'
type(x)

__main__.MyfirstClass

In [35]:
xy=MyfirstClass()
xy.name='Pierre' # Luego de realizada esta asignación "xy.name" es el "name" del objeto 'xy'
print(xy.name)          # Notar que el atributo 'name' no estaba definido anteriormente en MyfirstClass.
z=xy
z.name='Paul' # los atributos son objetos mutables.
print(xy.name)

Pierre
Paul


De manera similar a las funciones, podremos definir valores por defecto, para la instanciación de un nuevo objeto:


In [36]:
class Ratio():
    "Número Racional"
    def __init__(self,numerator,denominator): # Siempre usar "self" para referirse a los atributos
                                              # del objeto (variables internas)
        self.num=numerator
        self.den=denominator

In [37]:
q=Ratio(0,1) # Crea una variable "q" de tipo "Ratio" , donde el numerador es 0 y el denominador es 1
print(q.num)
print(q.den) 

0
1


## Métodos asociados al objeto

Dentro de la Clase definimos los métodos (funciones internas a los objetos) que los objetos requieren para realizar computaciones, acciones, etc. 


In [1]:
class Ratio():
    "rational number"
    def __init__(self,numerator,denominator):
        self.num=numerator
        self.den=denominator
    def val(self):
        return self.num/self.den

In [2]:
val(Ratio(0,1)) # Esto no funciona, recordar que 'val' es un método y no una función.

NameError: name 'val' is not defined

In [41]:
q=Ratio(0,1)
print(q.val())
print(Ratio.val(q))

0.0
0.0


## Sobrecarga de operadores/comandos (Overloading)

La "sobrecarga" de una función, operador, método, ya definido nos permite cambiar su significado. Por ejemplo, nos gustaria re-definir el operador "suma" $\textit{"+"}$, para nuestra nueva clase de objetos.    


In [ ]:
class Ratio():
    "rational number"
    def __init__(self,numerator=0,denominator=1):
        self.num=numerator
        self.den=denominator
        
    # Methods
    def val(self):
        return self.num/self.den
    
    #Overloading operators
    def __add__(self,other):    # Sobrecarga del operador '+'.
        return Ratio(self.num*other.den+self.den*other.num,self.den*other.den)
    def suma(self,other):    # Sobrecarga del operador '+'.
        return Ratio(self.num*other.den+self.den*other.num,self.den*other.den)
    def __str__(self):          # Sobrecarga necesaria para la función 'print'.
        return str(self.num)+'/'+str(self.den)  #Cómo devolvemos una cadena de caracteres, para que
                                                #la función print muestre algo para nuestro objeto. 
    def __mul__(self,other):    # Sobrecarga del operador '*'.
        return Ratio(self.num*other.num,self.den*other.den)
    def __int__(self): #Sobrecarga de la función 'int'.
        return int(self.val())
        
  #print(obj)----> print(str(obj))  

In [ ]:
q1=Ratio(2,3)
q2=Ratio(1,3)
q=q1 + q2 # q3= q1.suma(q2) # q3 = Ratio.suma(q1,q2)
print(q.num,q.den) # No es muy bonito, podemos arreglarlo?
print(q)
